{% set name = "pplpy" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 471b576a4c285758d27cc4a6f1b41afa29bfb9f3754a37f0520b35b6958eb8ce

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ppl
    - python
    - cysignals
    - cython
    - pip
    - gmp
    - mpfr
    - mpc
    - gmpy2
  run:
    - python
    - cysignals
    - gmp
    - mpfr
    - mpc
    - gmpy2
    - {{ pin_compatible("ppl", max_pin="x.x") }}

test:
  imports:
    - ppl

about:
  home: https://www.normaliz.uni-osnabrueck.de
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: This Python package provides a wrapper to the C++ Parma Polyhedra Library (PPL).
  dev_url: https://gitlab.com/videlec/pplpy

extra:
  recipe-maintainers:
    - isuruf
